apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs
    tier: frontend
spec:
  selector:
    app: karsajobs
    tier: frontend
  ports:
    - port: 8000
      nodePort: 32345
  type: NodePort