apiVersion: v1
kind: Service
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    tier: backend
spec:
  ports:
    - port: 8080
      nodePort: 31234
  selector:
    app: karsajobs
    tier: backend
  type: NodePort