apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: karsajobs
    tier: database
spec:
  selector:
    app: karsajobs
    tier: database
  ports:
    - port: 27017
  clusterIP: None 
  